nodeLinker: node-modules
enableGlobalCache: true
npmRegistryServer: "https://registry.npmjs.org"
enableScripts: true
enableTelemetry: false
logFilters:
  - level: discard
    pattern: "*gatsby-transformer-sharp*"
