[build]
  command = "YARN_ENABLE_SCRIPTS=1 yarn install --production=false && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "4.1.1"
  CI = "true"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  NODE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production.environment]
  NODE_ENV = "production"
