[build]
  command = "yarn install && yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "4.1.1"
  CI = "true"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  NODE_ENV = "development"
  YARN_ENABLE_SCRIPTS = "1"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[context.production.environment]
  NODE_ENV = "production"
