[build]
  command = "yarn install && yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "16"
  YARN_VERSION = "1.22.19"
  CI = "true"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  NODE_ENV = "development"
  YARN_ENABLE_SCRIPTS = "1"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production.environment]
  NODE_ENV = "production"
